### ISSUE TITLE
arguments is a reserved word in Javascript

### ISSUE THREAD

**Issue by Znack** [seek-oss/serverless-haskell#13]
Hello, thanks for great tool, I'm trying to launch some test project with it and have encountered the problem with Node environment, the error is:

```
START RequestId: 61730031-fc71-11e7-bc7b-35986d9cfc05 Version: $LATEST
Syntax error in module 'serverless-lambda-test': SyntaxError
    const arguments = options['arguments'];
                                         ^
SyntaxError: Identifier 'arguments' has already been declared
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
END RequestId: 61730031-fc71-11e7-bc7b-35986d9cfc05
REPORT RequestId: 61730031-fc71-11e7-bc7b-35986d9cfc05	Duration: 5.87 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 21 MB	
```

As I understand this happened because `arguments` is reserved word in Javascript, so we cannot declare `const` with a such name :)

If it matters I have used Node runtime 6.10 and default settings/project from README.md (so to reproduce it is enough to go through all steps from README.md).

**Comment by Znack** [comment]
Thanks for fast feedback, everything works like a charm now :)
