### ISSUE TITLE
Cannot read property 'schema' of undefined

### ISSUE THREAD

**Issue by westonplatter** [seek-oss/serverless-haskell#161]
I followed the instructions, 
```
stack new mypackage https://raw.githubusercontent.com/seek-oss/serverless-haskell/master/serverless-haskell.hsfiles
cd mypackage
npm install
stack build
sls invoke local -f mypackage-func
```

and got this, 
```
Cannot read property 'schema' of undefined
```

Here is the SLS debug info,
```
sls invoke local -f mypackage-func
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
 
  Type Error ---------------------------------------------
 
  Cannot read property 'schema' of undefined
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: Cannot read property 'schema' of undefined
    at new ServerlessPlugin (/Users/vifo/git/mypackage/node_modules/serverless-haskell/dist/index.js:115:35)
    at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:62:28)
    at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:102:14
    at Array.forEach (<anonymous>)
    at PluginManager.loadPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:98:13)
    at PluginManager.loadServicePlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:151:10)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:94:10)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:72:26
From previous event:
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:70:8)
    at /usr/local/lib/node_modules/serverless/bin/serverless:42:21
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           14.12.0
     Serverless Version:     1.43.0
```

I am opening this issue with the hopes of resolving this issue or updating the readme docs with steps to avert this issue for future users.

**Comment by westonplatter** [comment]
I created this issue too quick. 

I uninstalled & reinstall serverless and that fixed the issue.
