### ISSUE TITLE
`invoke local` is not supported

### ISSUE THREAD

**Issue by declension** [seek-oss/serverless-haskell#32]
Hi. New to Serverless so maybe I'm doing it wrong, but:

### Steps
 * Check out and build example project
 * Verify that `sls invoke hello -d "[1, 100, 10]"` correctly returns `"Highest value is 100"`
 * Then run `sls invoke local hello -d "[1, 100, 10]"`

### Expected
 * Same result, i.e. `"Highest value is 100"`

### Actual
Errors with:
```
{ Error: Cannot find module '/home/nick/workspace/GITHUB/serverless-haskell/example-project/serverless-haskell-example'                                                            
    at Function.Module._resolveFilename (module.js:547:15)                               
    at Function.Module._load (module.js:474:25)                                          
    at Module.require (module.js:596:17)    
    at require (internal/module.js:11:18)   
    at AwsInvokeLocal.invokeLocalNodeJs (/home/nick/workspace/GITHUB/serverless-haskell/example-project/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:258:33)       
    at AwsInvokeLocal.invokeLocal (/home/nick/workspace/GITHUB/serverless-haskell/example-project/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:125:19)             
    at AwsInvokeLocal.tryCatcher (/home/nick/workspace/GITHUB/serverless-haskell/example-project/node_modules/bluebird/js/release/util.js:16:23)                                   
    at Promise._settlePromiseFromHandler (/home/nick/workspace/GITHUB/serverless-haskell/example-project/node_modules/bluebird/js/release/promise.js:512:31)                       
    at Promise._settlePromise (/home/nick/workspace/GITHUB/serverless-haskell/example-project/node_modules/bluebird/js/release/promise.js:569:18)                                  
    at Promise._settlePromise0 (/home/nick/workspace/GITHUB/serverless-haskell/example-project/node_modules/bluebird/js/release/promise.js:614:10)                                 
    at Promise._settlePromises (/home/nick/workspace/GITHUB/serverless-haskell/example-project/node_modules/bluebird/js/release/promise.js:693:18)                                 
    at Async._drainQueue (/home/nick/workspace/GITHUB/serverless-haskell/example-project/node_modules/bluebird/js/release/async.js:133:16)                                         
    at Async._drainQueues (/home/nick/workspace/GITHUB/serverless-haskell/example-project/node_modules/bluebird/js/release/async.js:143:10)                                        
    at Immediate.Async.drainQueues (/home/nick/workspace/GITHUB/serverless-haskell/example-project/node_modules/bluebird/js/release/async.js:17:14)                                
    at runCallback (timers.js:794:20)       
    at tryOnImmediate (timers.js:752:5)     
    at processImmediate [as _immediateCallback] (timers.js:729:5) code: 'MODULE_NOT_FOUND' }                                                                                       
Done in 0.66s.                              
```

**Comment by koterpillar** [comment]
You're right - `invoke local` isn't supported, as it needs to be implemented separately to the actual invoke. I'll add a note to README for now, but this is definitely something I'd want to implement later.

As a workaround, you can use `stack exec` and then provide the input JSON on the standard input.

**Comment by declension** [comment]
Thanks @koterpillar. Yes I ended up using that workaround but good to know it wasn't just me (so +1 for README too). Let me know if I can help!

**Comment by JBetz** [comment]
Is there any way to use a local HTTP API Gateway without this command?

**Comment by declension** [comment]
@JBetz I recall that I created some horrendous APIGW wrapper JSON to pipe to the `stack exec` process directly, and that worked - is that what you're getting at?

**Comment by JBetz** [comment]
@declension As long I can test it with actual HTTP, that should work.

**Comment by declension** [comment]
@JBetz no sorry - this was using good ol' unix pipes, not actual HTTP. 

Personally I wasn't worried about HTTP functioning how I thought it should in Api Gateway (it did, give or take), more dealing with the complex JSON that API GW sends.

_That_ was done like this, assuming your stack app is called `my-handler` and it's called `my-handler` and has an endpoint `/foo/<bar>`.

```bash
$ stack exec my-handler <<< '{"resource": "my-resource", "path": "/foo", "httpMethod": "GET", "pathParameters": {"bar": "baz"}, "requestContext": {"requestId": "abcde", "accountId": "1234", "resourceId": "abcd", "stage": "dev", "identity": {}, "httpMethod": "GET", "resourcePath": "/foo", "apiId": "abc"}}'
```
You can also get the AWS UI to generate some of this boilerplate for you, I later found...

**Comment by koterpillar** [comment]
Accidentally fixed this while playing with serverless-offline, see #51. As I understand it, serverless-offline is the real target here, I'll keep working on that part.
