### ISSUE TITLE
Package version mismatch: NPM: 0.7.1, Stack: 0.6.3 on lts-12.2

### ISSUE THREAD

**Issue by Tehnix** [seek-oss/serverless-haskell#58]
With `lts-12.2` I'm currently getting a package version mismatch, which I'm not quite sure how to debug :/

A minimal project that runs into it is https://github.com/Tehnix/ServHs/tree/7eb997d5e39cd256bd900b050a605846d9f28d68.

```
$ SLS_DEBUG=* yarn sls invoke local --function entry
...
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Invoke invoke:local
Serverless: Building handler with Stack...
ServHs-0.1.0.0: unregistering (local file changes: README.md)
ServHs-0.1.0.0: build (lib + exe)
Preprocessing library for ServHs-0.1.0.0..
Building library for ServHs-0.1.0.0..
ignoring (possibly broken) abi-depends field for packages
Preprocessing executable 'entry' for ServHs-0.1.0.0..
Building executable 'entry' for ServHs-0.1.0.0..
ServHs-0.1.0.0: copy/register
Installing library in /Users/tehnix/GitHub/Tehnix/ServHs/.stack-work/install/x86_64-osx/lts-12.2/8.4.3/lib/x86_64-osx-ghc-8.4.3/ServHs-0.1.0.0-EOEdRPhD4y0Iek8gkVmCM0
Installing executable entry in /Users/tehnix/GitHub/Tehnix/ServHs/.stack-work/install/x86_64-osx/lts-12.2/8.4.3/bin
Registering library for ServHs-0.1.0.0..
Serverless: Package version mismatch: NPM: 0.7.1, Stack: 0.6.3. Versions must be in sync to work correctly.

  Error --------------------------------------------------

  Package version mismatch.

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Package version mismatch.
    at ServerlessPlugin.assertServerlessPackageVersionsMatch (/Users/tehnix/GitHub/Tehnix/ServHs/node_modules/serverless-haskell/index.js:175:19)
    at service.getAllFunctions.forEach.funcName (/Users/tehnix/GitHub/Tehnix/ServHs/node_modules/serverless-haskell/index.js:258:18)
    at Array.forEach (<anonymous>)
    at ServerlessPlugin.buildHandlers (/Users/tehnix/GitHub/Tehnix/ServHs/node_modules/serverless-haskell/index.js:240:35)
    at ServerlessPlugin.buildHandlersLocal (/Users/tehnix/GitHub/Tehnix/ServHs/node_modules/serverless-haskell/index.js:213:14)
    at BbPromise.reduce (/Users/tehnix/GitHub/Tehnix/ServHs/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/Users/tehnix/GitHub/Tehnix/ServHs/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/Users/tehnix/GitHub/Tehnix/ServHs/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/Users/tehnix/GitHub/Tehnix/ServHs/node_modules/serverless/lib/Serverless.js:163:33)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/Users/tehnix/GitHub/Tehnix/ServHs/node_modules/serverless/lib/Serverless.js:150:8)
    at serverless.init.then (/Users/tehnix/GitHub/Tehnix/ServHs/node_modules/serverless/bin/serverless:42:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.7.0
     Serverless Version:     1.28.0

error Command failed with exit code 1
```

- stack version 1.7.1
- npm version 6.2.0
- yarn version 1.7.0

Let me know if you need any other details!

**Comment by koterpillar** [comment]
Please install the matching version of the npm package explicitly.

**Comment by Tehnix** [comment]
Ah, nevermind, digged through the source and could read it was trying to match the npm installed one with the stack installed one.

Got it working by throwing a newer version in `extra-deps` in my `stack.yaml`,

```
resolver: lts-12.2
extra-deps:
- serverless-haskell-0.7.1
packages:
- .
```

I don't know if something, maybe added documentation, could be done to alleviate this. Anyways, I'll close this issue :)

**Comment by koterpillar** [comment]
@Tehnix I've tried to address your concerns in #59, see dc497dff9ec0e6b602eb185cd94b17797ca8ed69 - would that have helped you?

**Comment by Tehnix** [comment]
@koterpillar perfect! I was actually in the middle of PRing to `index.js` myself, but this is perfect :)
