### ISSUE TITLE
Socket hangs up after some time in serverless offline, and keeps going in invoke local

### ISSUE THREAD

**Issue by Tehnix** [seek-oss/serverless-haskell#62]
I am not sure if this is related to https://github.com/seek-oss/serverless-haskell/pull/28, but sockets seem to hang up both when using `serverless offline start` and `invoke local`.

```
$ yarn sls offline start
Serverless: Building handler with Stack...
...
Serverless: GET /hello/bla (λ: gateway-entry)
This should go to logs
Serverless: [200] {"body":"Hello, bla\n","headers":{},"statusCode":200}
Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at TLSSocket.socketOnEnd (_http_client.js:416:23)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
```

```
$ yarn sls invoke local --function entry --data '{}'
...
This should go to logs
Object (fromList [])
"Went into handler"
Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at TLSSocket.socketOnEnd (_http_client.js:416:23)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
```

I'd also expect `invoke local` to exit immediately after the response, but I am not sure what the intended effect is here.

**Comment by koterpillar** [comment]
Looks like https://github.com/serverless/serverless/issues/5138 and https://github.com/serverless/serverless/issues/5133.

**Comment by Tehnix** [comment]
Ah, indeed, that resolves both issues :)

I've pinned my node version, via nodenv, to 8.10.0 in my project, which it also should be, to match the version it deploys to.

**Comment by koterpillar** [comment]
Node version doesn't really matter, as the only piece of JavaScript uploaded to AWS is the generated handler, and it has no dependencies.
